[project]
name = "stacksdegens"
authors = []
description = ""
telemetry = true
requirements = []

[contracts.ft-trait]
path = "contracts/ft-trait.clar"
depends_on = []

[contracts.nft-trait]
path = "contracts/nft-trait.clar"
depends_on = []

[contracts.trustless-rewards]
path = "contracts/trustless-rewards.clar"
depends_on = ["nft-trait", "ft-trait"]

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false