[project]
name = "customizable-nfts"
authors = []
description = ""
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"
[contracts.backgrounds]
path = "contracts/backgrounds.clar"

[contracts.cars]
path = "contracts/cars.clar"

[contracts.component-nft]
path = "contracts/component-nft.clar"

[contracts.degens]
path = "contracts/degens.clar"

[contracts.heads]
path = "contracts/heads.clar"

[contracts.miami-degens]
path = "contracts/miami-degens.clar"

[contracts.nft-trait]
path = "contracts/nft-trait.clar"

[contracts.nyc-degens]
path = "contracts/nyc-degens.clar"

[contracts.rims]
path = "contracts/rims.clar"

[contracts.sip-010-trait-ft-standard]
path = "contracts/sip-010-trait-ft-standard.clar"

[contracts.token-metadata-update-notify]
path = "contracts/token-metadata-update-notify.clar"

[contracts.upgrade-contract]
path = "contracts/upgrade-contract.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
