export const oldToNewComponentNames = {
  miami: {
    background: {
      'Luna purple': 'Purple',
      'Lost orange': 'Orange',
      'Sunset mist': 'Sunset',
    },
    car: {
      Grey: 'LamboGrey',
      Blue: 'LamboBlue',
      Red: 'LamboRed',
      Gold: 'LamboGold',
      Emrald: 'LamboEmerald',
      Pearlescent: 'LamboPearlescent',
    },
    face: {
      None: 'None',
      Cigar: 'Cigar',
      'Gold-teeth': 'GoldTeeth',
      Bandana: 'Bandana',
      'Flame-eyes': 'FlameEyes',
      Sunglasses: 'Sunglasses',
    },
    head: {
      None: 'None',
      Sword: 'Sword',
      Party: 'Party',
      Bullet: 'Bullet',
      Crown: 'Crown',
      Pfizer: 'Syringe',
    },
    rims: {
      Grey: 'SportyGrey',
      Black: 'SportyBlack',
      Blue: 'SportyBlue',
      Gold: 'SportyGold',
      Lime: 'SportyLime',
      Pearlescent: 'SportyPearlescent',
    },
  },
  nyc: {
    background: {
      Goldie: 'Goldie',
      Emeraldie: 'Emerald',
      Purplie: 'DarkPurple',
    },
    car: {
      Grey: 'BentleyGrey',
      White: 'BentleyWhite',
      Black: 'BentleyBlack',
      Gold: 'BentleyGold',
      Purple: 'BentleyPurple',
      Midnight: 'BentleyMidnight',
      Blood: 'BentleyBlood',
    },
    face: {
      Kaonashi: 'Kaonashi',
      Lips: 'Lips',
      'Big-Smile': 'BigSmile',
      Memeglass: 'MemeGlasses',
      'White-eyes': 'WhiteEyes',
      Elf: 'Elf',
      Cuban: 'Cuban',
      'Nose-Pierceing': 'NosePiercing',
      Vampire: 'Vampire',
    },
    head: {
      Tomahwak: 'Tomahawk',
      'Great-Hair': 'GreatHair',
      PUBG: 'PUBG',
      'Bitcoin-police': 'BitcoinPolice',
      Samurai: 'Samurai',
      CowBoy: 'Cowboy',
      Antenna: 'Antenna',
      Openminded: 'OpenMinded',
    },
    rims: {
      Silver: 'ClassySilver',
      Dark: 'ClassyDark',
      Cream: 'ClassyCream',
      Gold: 'ClassyGold',
      White: 'ClassyWhite',
    },
  },
};
