[network]
name = "devnet"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw"
balance = 100_000_000_000_000
# secret_key: 753b7cc01a1a2e86221266a154af739463fce51219d97e4f856cd7200c3bd2a601
# stx_address: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM
# btc_address: mqVnk6NPRdhntvfm4hh9vvjiRkFDUuSYsH

[accounts.wallet_1]
mnemonic = "sell invite acquire kitten bamboo drastic jelly vivid peace spawn twice guilt pave pen trash pretty park cube fragile unaware remain midnight betray rebuild"
balance = 100_000_000_000_000
# secret_key: 7287ba251d44a4d3fd9276c88ce34c5c52a038955511cccaf77e61068649c17801
# stx_address: ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2ZQ8YPD5
# btc_address: mr1iPkD9N3RJZZxXRk7xF9d36gffa6exNC

[accounts.wallet_2]
mnemonic = "hold excess usual excess ring elephant install account glad dry fragile donkey gaze humble truck breeze nation gasp vacuum limb head keep delay hospital"
balance = 100_000_000_000_000
# secret_key: 530d9f61984c888536871c6573073bdfc0058896dc1adfe9a6a10dfacadc209101
# stx_address: ST2CY5V39NHDPWSXMW9QDT3HC3GD6Q6XX4CFRK9AG
# btc_address: muYdXKmX9bByAueDe6KFfHd5Ff1gdN9ErG

[accounts.wallet_3]
mnemonic = "cycle puppy glare enroll cost improve round trend wrist mushroom scorpion tower claim oppose clever elephant dinosaur eight problem before frozen dune wagon high"
balance = 100_000_000_000_000
# secret_key: d655b2523bcd65e34889725c73064feb17ceb796831c0e111ba1a552b0f31b3901
# stx_address: ST2JHG361ZXG51QTKY2NQCVBPPRRE2KZB1HR05NNC
# btc_address: mvZtbibDAAA3WLpY7zXXFqRa3T4XSknBX7

[accounts.wallet_4]
mnemonic = "board list obtain sugar hour worth raven scout denial thunder horse logic fury scorpion fold genuine phrase wealth news aim below celery when cabin"
balance = 100_000_000_000_000
# secret_key: f9d7206a47f14d2870c163ebab4bf3e70d18f5d14ce1031f3902fbbc894fe4c701
# stx_address: ST2NEB84ASENDXKYGJPQW86YXQCEFEX2ZQPG87ND
# btc_address: mg1C76bNTutiCDV3t9nWhZs3Dc8LzUufj8

[accounts.wallet_5]
mnemonic = "hurry aunt blame peanut heavy update captain human rice crime juice adult scale device promote vast project quiz unit note reform update climb purchase"
balance = 100_000_000_000_000
# secret_key: 3eccc5dac8056590432db6a35d52b9896876a3d5cbdea53b72400bc9c2099fe801
# stx_address: ST2REHHS5J3CERCRBEPMGH7921Q6PYKAADT7JP2VB
# btc_address: mweN5WVqadScHdA81aATSdcVr4B6dNokqx

[accounts.wallet_6]
mnemonic = "area desk dutch sign gold cricket dawn toward giggle vibrant indoor bench warfare wagon number tiny universe sand talk dilemma pottery bone trap buddy"
balance = 100_000_000_000_000
# secret_key: 7036b29cb5e235e5fd9b09ae3e8eec4404e44906814d5d01cbca968a60ed4bfb01
# stx_address: ST3AM1A56AK2C1XAFJ4115ZSV26EB49BVQ10MGCS0
# btc_address: mzxXgV6e4BZSsz8zVHm3TmqbECt7mbuErt

[accounts.wallet_7]
mnemonic = "prevent gallery kind limb income control noise together echo rival record wedding sense uncover school version force bleak nuclear include danger skirt enact arrow"
balance = 100_000_000_000_000
# secret_key: b463f0df6c05d2f156393eee73f8016c5372caa0e9e29a901bb7171d90dc4f1401
# stx_address: ST3PF13W7Z0RRM42A8VZRVFQ75SV1K26RXEP8YGKJ
# btc_address: n37mwmru2oaVosgfuvzBwgV2ysCQRrLko7

[accounts.wallet_8]
mnemonic = "female adjust gallery certain visit token during great side clown fitness like hurt clip knife warm bench start reunion globe detail dream depend fortune"
balance = 100_000_000_000_000
# secret_key: 6a1a754ba863d7bab14adbbc3f8ebb090af9e871ace621d3e5ab634e1422885e01
# stx_address: ST3NBRSFKX28FQ2ZJ1MAKX58HKHSDGNV5N7R21XCP
# btc_address: n2v875jbJ4RjBnTjgbfikDfnwsDV5iUByw

[accounts.wallet_9]
mnemonic = "pair comfort obscure dolphin swallow sun side stick inspire game language fetch marine gift crack rubber kiss alien regular kitchen guard venture hold lady"
balance = 100_000_000_000_000
# secret_key: 12ef02bbdaff97eb233bdd7cb4505c84ebb9650b515a43cd6106329be80bc13801
# stx_address: ST268BPGYGM8R960QC735ERJ5QCP5C31W106XXJKA
# btc_address: mtKyF7TqUUdtzGYDHqGTdPq7jREk3ZxU2g

[accounts.wallet_10]
mnemonic = "naive boil belt buyer struggle novel grain quiz actual effort hobby fog tide capable chest guard mistake learn wrestle require crawl reveal bus make"
balance = 100_000_000_000_000
# secret_key: d21124475d9bd26af0675a82b30bb50b22ba0058662581d56db59f91c046121b01
# stx_address: ST3YJFJ3Y3XS28J7PD8CBD9CWCMHHGEXXVKNBJAT1
# btc_address: n4bWumeMBL28m149ncmc6zVJdHNkFSfMKY

[accounts.wallet_11]
mnemonic = "inch solar spin cricket regret flame intact grief surround update harsh sort mule iron busy helmet oak come mutual under foam blast goddess cupboard"
balance = 100_000_000_000_000
# secret_key: cde8779a67a580cda053be50cdc55c1c527c7430b70c802fd1f83a3d8b342e3c01
# stx_address: ST3MT8Q0E61GSB3HJ0GQ510VPHMMNGGKPZKJMB9PK
# btc_address: n2pLdex7bRmMhZcy4RRk2tPipnVuHuURnd

[accounts.wallet_12]
mnemonic = "inquiry across heavy rose loyal flight salad tongue genius enroll buzz pond invite tree tower legal term embrace tooth anchor inside badge guitar drum"
balance = 100_000_000_000_000
# secret_key: 257c74ed7940b0892d403f827b4a1c5a6a65a219e309aec80a6df042ecaa1a3b01
# stx_address: ST3XRFYD6A2A9T8QWT9NFXHP8XFCDEQ30EFZC8CMF
# btc_address: n4SvnvdrhEiCeFbKyVqRFB4TguPXPXCaLQ

[accounts.wallet_13]
mnemonic = "nephew impulse stand theory spray situate poem title attend tornado broken spin pony neutral click gun enjoy youth radio credit suffer soccer wheel cram"
balance = 100_000_000_000_000
# secret_key: 8b7220f8d4dd62f5eec35e84365454c6b4911bd55121164de11eff65439ae2e901
# stx_address: STRRXZWHE3WC9WF11WJX3XFDB19BNCRYSJH9EP5
# btc_address: mff9FBWeBv9rMCamTq36wJbUyTdjzDzpMf

[accounts.wallet_14]
mnemonic = "athlete despair badge witness winter patrol that bridge account notice approve economy first spawn because furnace clump melt column latin risk toss chunk trouble"
balance = 100_000_000_000_000
# secret_key: c9bf74fa04edd1e0fee01e425cdae68215259045100a0f4a02b72f3cef6ba0a301
# stx_address: ST273Z5AWCAB0P11WP2QRNMR705QYP3VQ4T1JDAZP
# btc_address: mtV6R9b3Pgnh78z95T8Uh7MF5q5spD98u6

[accounts.wallet_15]
mnemonic = "dice tank alter true physical illegal badge receive author issue barrel cup damage loud athlete cat accuse paddle response caught asthma crumble wine toy"
balance = 100_000_000_000_000
# secret_key: ff0c19bcabe7be046c33fd05dd85bbdb56041bb8b9f13558a6a8b0c64d26ac9f01
# stx_address: ST2D1SPJ6HZ2BKKH55Z8DQDMQ409KG6H3FVVFZNMX
# btc_address: muZpvK5EnuVb3qoj7bP4G1TwwkyvmtLFfY

[accounts.wallet_16]
mnemonic = "answer never focus winner october universe fame aerobic oval loyal chef black choose theory assist column reform impose view motor exact parent return burst"
balance = 100_000_000_000_000
# secret_key: a454abd6bbb5ecf57f5d9f93aa79fd6382b76e250794af9245010b1ebcbf0dff01
# stx_address: STZHX0QH4P4ARZCC1P8AVD8KXYH0QNE7SZNE5WAP
# btc_address: mmGhR7d2b3f9U4LZGjWjiGrq1Tf8teVwe7

[accounts.wallet_17]
mnemonic = "quality rigid medal pill chat actress fantasy mansion rice enter crash foster million indicate boil cancel dirt stuff faint loyal again spy obtain educate"
balance = 100_000_000_000_000
# secret_key: f529ff709d9e0d74c140ce296ffaa7f3fe9674c79c27666f3785f207aeeb56a401
# stx_address: ST3S2ZW2CHKJPGMJN4WMAT9DH30YA2RYMPCV6KAJD
# btc_address: n3bXFKAfKuQEQkHW2VU7A8eZCpXhuscuhV

[accounts.wallet_18]
mnemonic = "guide task canvas spray pave mother domain age air trophy kick tape install merge earn harbor language cannon penalty omit dynamic arctic tip dumb"
balance = 100_000_000_000_000
# secret_key: d5066c61364fc9b261096ad332db4f7fbe8d464607ff2751fa28cbce3ff9c8e401
# stx_address: ST3RJKHMQ134F8XVR3X3538ATS18J1RB0C96D7FG3
# btc_address: n3W7Buzy4eSveaDq1uMtrP8C4jF745FASW

[accounts.wallet_19]
mnemonic = "betray desk drive seven party saddle okay indoor raise upper goose clap teach satoshi dentist camp rebuild short notable combine gaze kitchen style peace"
balance = 100_000_000_000_000
# secret_key: 53e8ba702454d6a8e14750b9a292d39f57639c5123662fa008949c9fe7a3746401
# stx_address: ST4JJ20RC02MESCW46CDJCQ3HBPP6D9XW0YEKADF
# btc_address: mgMPXhzWTJWwibz389Gi8wCRoZZsp3xFtJ

[accounts.wallet_20]
mnemonic = "travel wire add sort abstract canal off alcohol rigid orient dice advance flip render blanket witness ranch perfect quarter govern skill climb planet liquid"
balance = 100_000_000_000_000
# secret_key: d4bb10aa2d481dd276c859d2403eeee0742f0805cdbf42a8383ad14278372c9601
# stx_address: ST2RNBTWA0SX7SRRG6SFJKC2EC5NHYF80MS5JB4MG
# btc_address: mwgcpqeDAAguM9pHLwR8aoaSAqVi3pDAWT

[accounts.faucet]
mnemonic = "shadow private easily thought say logic fault paddle word top book during ignore notable orange flight clock image wealth health outside kitten belt reform"
balance = 100_000_000_000_000
# secret_key: de433bdfa14ec43aa1098d5be594c8ffb20a31485ff9de2923b2689471c401b801
# stx_address: STNHKEPYEPJ8ET55ZZ0M5A34J0R3N5FM2CMMMAZ6
# btc_address: mjSrB3wS4xab3kYqFktwBzfTdPg367ZJ2d

[devnet]
disable_stacks_explorer = false
disable_stacks_api = false
# disable_bitcoin_explorer = true
# working_dir = "tmp/devnet"
# stacks_node_events_observers = ["host.docker.internal:8002"]
# miner_mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw"
# miner_derivation_path = "m/44'/5757'/0'/0/0"
# faucet_mnemonic = "shadow private easily thought say logic fault paddle word top book during ignore notable orange flight clock image wealth health outside kitten belt reform"
# faucet_derivation_path = "m/44'/5757'/0'/0/0"
# orchestrator_port = 20445
# bitcoin_node_p2p_port = 18444
# bitcoin_node_rpc_port = 18443
# bitcoin_node_username = "devnet"
# bitcoin_node_password = "devnet"
bitcoin_controller_block_time = 5_000
# stacks_node_rpc_port = 20443
# stacks_node_p2p_port = 20444
# stacks_api_port = 3999
# stacks_api_events_port = 3700
# bitcoin_explorer_port = 8001
# stacks_explorer_port = 8000
# postgres_port = 5432
# postgres_username = "postgres"
# postgres_password = "postgres"
# postgres_database = "postgres"
# bitcoin_node_image_url = "quay.io/hirosystems/bitcoind:devnet-v2"
# stacks_node_image_url = "localhost:5000/stacks-node:devnet-v2"
# stacks_api_image_url = "hirosystems/stacks-blockchain-api:latest"
# stacks_explorer_image_url = "hirosystems/explorer:latest"
# bitcoin_explorer_image_url = "quay.io/hirosystems/bitcoin-explorer:devnet"
# postgres_image_url = "postgres:alpine"
# enable_hyperchain_node = true
# hyperchain_image_url = "hirosystems/hyperchains:103-merge-stretch"
# hyperchain_leader_mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw"
# hyperchain_leader_derivation_path = "m/44'/5757'/0'/0/0"
# hyperchain_node_rpc_port = 30443
# hyperchain_node_p2p_port = 30444
# hyperchain_events_ingestion_port = 30445
# hyperchain_node_events_observers = ["host.docker.internal:8002"]


# Send some stacking orders
[[devnet.pox_stacking_orders]]
start_at_cycle = 3
duration = 12
wallet = "wallet_1"
slots = 2
btc_address = "mr1iPkD9N3RJZZxXRk7xF9d36gffa6exNC"

[[devnet.pox_stacking_orders]]
start_at_cycle = 3
duration = 12
wallet = "wallet_2"
slots = 1
btc_address = "muYdXKmX9bByAueDe6KFfHd5Ff1gdN9ErG"

[[devnet.pox_stacking_orders]]
start_at_cycle = 3
duration = 12
wallet = "wallet_3"
slots = 1
btc_address = "mvZtbibDAAA3WLpY7zXXFqRa3T4XSknBX7"
