export const car_json_url_hash = {
  BentleyBlack: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/BentleyBlack.json',
  BentleyBlood: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/BentleyBlood.json',
  BentleyGold: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/BentleyGold.json',
  BentleyGrey: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/BentleyGrey.json',
  BentleyMidnight: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/BentleyMidnight.json',
  BentleyPurple: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/BentleyPurple.json',
  BentleyWhite: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/BentleyWhite.json',
  LamboBlue: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/LamboBlue.json',
  LamboEmerald: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/LamboEmerald.json',
  LamboGold: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/LamboGold.json',
  LamboGrey: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/LamboGrey.json',
  LamboPearlescent: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/LamboPearlescent.json',
  LamboRed: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/LamboRed.json',
};
export const car_img_marketplace_hash = {
  BentleyBlack: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/BentleyBlack.png',
  BentleyBlood: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/BentleyBlood.png',
  BentleyGold: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/BentleyGold.png',
  BentleyGrey: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/BentleyGrey.png',
  BentleyMidnight: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/BentleyMidnight.png',
  BentleyPurple: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/BentleyPurple.png',
  BentleyWhite: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/BentleyWhite.png',
  LamboBlue: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/LamboBlue.png',
  LamboEmerald: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/LamboEmerald.png',
  LamboGold: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/LamboGold.png',
  LamboGrey: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/LamboGrey.png',
  LamboPearlescent: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/LamboPearlescent.png',
  LamboRed: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/LamboRed.png',
};
export const car_img_utility_hash = {
  BentleyBlack: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/BentleyBlack.png',
  BentleyBlood: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/BentleyBlood.png',
  BentleyGold: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/BentleyGold.png',
  BentleyGrey: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/BentleyGrey.png',
  BentleyMidnight: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/BentleyMidnight.png',
  BentleyPurple: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/BentleyPurple.png',
  BentleyWhite: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/BentleyWhite.png',
  LamboBlue: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/LamboBlue.png',
  LamboEmerald: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/LamboEmerald.png',
  LamboGold: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/LamboGold.png',
  LamboGrey: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/LamboGrey.png',
  LamboPearlescent: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/LamboPearlescent.png',
  LamboRed: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/LamboRed.png',
};
