export const car_json_url_hash = {
  BentleyBlack: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/BentleyBlack.json',
  BentleyBlood: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/BentleyBlood.json',
  BentleyGold: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/BentleyGold.json',
  BentleyGrey: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/BentleyGrey.json',
  BentleyMidnight: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/BentleyMidnight.json',
  BentleyPurple: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/BentleyPurple.json',
  BentleyWhite: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/BentleyWhite.json',
  LamboBlue: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/LamboBlue.json',
  LamboEmerald: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/LamboEmerald.json',
  LamboGold: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/LamboGold.json',
  LamboGrey: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/LamboGrey.json',
  LamboPearlescent: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/LamboPearlescent.json',
  LamboRed: 'ipfs://QmUeeP62n6izm2skUjr17RcVdr5b5PsTyGQwU8GMRg92ux/LamboRed.json',
};
export const car_img_marketplace_hash = {
  BentleyBlack: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/BentleyBlack.json',
  BentleyBlood: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/BentleyBlood.json',
  BentleyGold: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/BentleyGold.json',
  BentleyGrey: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/BentleyGrey.json',
  BentleyMidnight: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/BentleyMidnight.json',
  BentleyPurple: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/BentleyPurple.json',
  BentleyWhite: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/BentleyWhite.json',
  LamboBlue: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/LamboBlue.json',
  LamboEmerald: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/LamboEmerald.json',
  LamboGold: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/LamboGold.json',
  LamboGrey: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/LamboGrey.json',
  LamboPearlescent: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/LamboPearlescent.json',
  LamboRed: 'ipfs://QmYoRfeG8ucG27hyAaHwvsquHP5LrAGNeEncML1BkCcit1/LamboRed.json',
};
export const car_img_utility_hash = {
  BentleyBlack: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/BentleyBlack.json',
  BentleyBlood: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/BentleyBlood.json',
  BentleyGold: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/BentleyGold.json',
  BentleyGrey: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/BentleyGrey.json',
  BentleyMidnight: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/BentleyMidnight.json',
  BentleyPurple: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/BentleyPurple.json',
  BentleyWhite: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/BentleyWhite.json',
  LamboBlue: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/LamboBlue.json',
  LamboEmerald: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/LamboEmerald.json',
  LamboGold: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/LamboGold.json',
  LamboGrey: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/LamboGrey.json',
  LamboPearlescent: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/LamboPearlescent.json',
  LamboRed: 'ipfs://QmeCL653FLxAfdT8wGkHxhwHSdEfPBH4WF8h9Hz6XDbi4u/LamboRed.json',
};
