export const rims_json_url_hash = {
  ClassyCream: 'ipfs://QmdbWpM18AdKzaomZQRnNQotmXtPtRX9mAkht13TbUaQ32/ClassyCream.json',
  ClassyDark: 'ipfs://QmdbWpM18AdKzaomZQRnNQotmXtPtRX9mAkht13TbUaQ32/ClassyDark.json',
  ClassyGold: 'ipfs://QmdbWpM18AdKzaomZQRnNQotmXtPtRX9mAkht13TbUaQ32/ClassyGold.json',
  ClassySilver: 'ipfs://QmdbWpM18AdKzaomZQRnNQotmXtPtRX9mAkht13TbUaQ32/ClassySilver.json',
  ClassyWhite: 'ipfs://QmdbWpM18AdKzaomZQRnNQotmXtPtRX9mAkht13TbUaQ32/ClassyWhite.json',
  SportyBlack: 'ipfs://QmdbWpM18AdKzaomZQRnNQotmXtPtRX9mAkht13TbUaQ32/SportyBlack.json',
  SportyBlue: 'ipfs://QmdbWpM18AdKzaomZQRnNQotmXtPtRX9mAkht13TbUaQ32/SportyBlue.json',
  SportyGold: 'ipfs://QmdbWpM18AdKzaomZQRnNQotmXtPtRX9mAkht13TbUaQ32/SportyGold.json',
  SportyGrey: 'ipfs://QmdbWpM18AdKzaomZQRnNQotmXtPtRX9mAkht13TbUaQ32/SportyGrey.json',
  SportyLime: 'ipfs://QmdbWpM18AdKzaomZQRnNQotmXtPtRX9mAkht13TbUaQ32/SportyLime.json',
  SportyPearlescent: 'ipfs://QmdbWpM18AdKzaomZQRnNQotmXtPtRX9mAkht13TbUaQ32/SportyPearlescent.json',
};
export const rims_img_marketplace_hash = {
  ClassyCream: 'ipfs://QmUAeq2AoLPPednjPxmZzstG3yDHR7fqs7mK3q8oQg2qRV/ClassyCream.png',
  ClassyDark: 'ipfs://QmUAeq2AoLPPednjPxmZzstG3yDHR7fqs7mK3q8oQg2qRV/ClassyDark.png',
  ClassyGold: 'ipfs://QmUAeq2AoLPPednjPxmZzstG3yDHR7fqs7mK3q8oQg2qRV/ClassyGold.png',
  ClassySilver: 'ipfs://QmUAeq2AoLPPednjPxmZzstG3yDHR7fqs7mK3q8oQg2qRV/ClassySilver.png',
  ClassyWhite: 'ipfs://QmUAeq2AoLPPednjPxmZzstG3yDHR7fqs7mK3q8oQg2qRV/ClassyWhite.png',
  SportyBlack: 'ipfs://QmUAeq2AoLPPednjPxmZzstG3yDHR7fqs7mK3q8oQg2qRV/SportyBlack.png',
  SportyBlue: 'ipfs://QmUAeq2AoLPPednjPxmZzstG3yDHR7fqs7mK3q8oQg2qRV/SportyBlue.png',
  SportyGold: 'ipfs://QmUAeq2AoLPPednjPxmZzstG3yDHR7fqs7mK3q8oQg2qRV/SportyGold.png',
  SportyGrey: 'ipfs://QmUAeq2AoLPPednjPxmZzstG3yDHR7fqs7mK3q8oQg2qRV/SportyGrey.png',
  SportyLime: 'ipfs://QmUAeq2AoLPPednjPxmZzstG3yDHR7fqs7mK3q8oQg2qRV/SportyLime.png',
  SportyPearlescent: 'ipfs://QmUAeq2AoLPPednjPxmZzstG3yDHR7fqs7mK3q8oQg2qRV/SportyPearlescent.png',
};
export const rims_img_utility_hash = {
  ClassyCream: 'ipfs://QmWBHgQFLKpXW8EnU6LeRXcU2iZRCpsSMCgfnb7G6obA31/ClassyCream.png',
  ClassyDark: 'ipfs://QmWBHgQFLKpXW8EnU6LeRXcU2iZRCpsSMCgfnb7G6obA31/ClassyDark.png',
  ClassyGold: 'ipfs://QmWBHgQFLKpXW8EnU6LeRXcU2iZRCpsSMCgfnb7G6obA31/ClassyGold.png',
  ClassySilver: 'ipfs://QmWBHgQFLKpXW8EnU6LeRXcU2iZRCpsSMCgfnb7G6obA31/ClassySilver.png',
  ClassyWhite: 'ipfs://QmWBHgQFLKpXW8EnU6LeRXcU2iZRCpsSMCgfnb7G6obA31/ClassyWhite.png',
  SportyBlack: 'ipfs://QmWBHgQFLKpXW8EnU6LeRXcU2iZRCpsSMCgfnb7G6obA31/SportyBlack.png',
  SportyBlue: 'ipfs://QmWBHgQFLKpXW8EnU6LeRXcU2iZRCpsSMCgfnb7G6obA31/SportyBlue.png',
  SportyGold: 'ipfs://QmWBHgQFLKpXW8EnU6LeRXcU2iZRCpsSMCgfnb7G6obA31/SportyGold.png',
  SportyGrey: 'ipfs://QmWBHgQFLKpXW8EnU6LeRXcU2iZRCpsSMCgfnb7G6obA31/SportyGrey.png',
  SportyLime: 'ipfs://QmWBHgQFLKpXW8EnU6LeRXcU2iZRCpsSMCgfnb7G6obA31/SportyLime.png',
  SportyPearlescent: 'ipfs://QmWBHgQFLKpXW8EnU6LeRXcU2iZRCpsSMCgfnb7G6obA31/SportyPearlescent.png',
};
