[project]
name = 'bns-collection'
description = ''
authors = []
telemetry = false
cache_dir = '.cache'
requirements = []
[contracts.basic-nefete]
path = 'contracts/basic-nefete.clar'
clarity_version = 1
epoch = 2.0

[contracts.bitcoin-degens]
path = 'contracts/bitcoin-degens.clar'
clarity_version = 1
epoch = 2.0

[contracts.bns]
path = 'contracts/bns.clar'
clarity_version = 1
epoch = 2.0

[contracts.bnsx-fake]
path = 'contracts/bnsx-fake.clar'
clarity_version = 1
epoch = 2.0

[contracts.conversions]
path = 'contracts/conversions.clar'
clarity_version = 1
epoch = 2.0

[contracts.name-bns]
path = 'contracts/name-bns.clar'
clarity_version = 1
epoch = 2.0

[contracts.name-only-bnsx]
path = 'contracts/name-only-bnsx.clar'
clarity_version = 1
epoch = 2.0

[contracts.name-without-bnsx]
path = 'contracts/name-without-bnsx.clar'
clarity_version = 1
epoch = 2.0

[contracts.naming]
path = 'contracts/naming.clar'
clarity_version = 1
epoch = 2.0

[contracts.nft-trait]
path = 'contracts/nft-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.og-bitcoin-degens]
path = 'contracts/og-bitcoin-degens.clar'
clarity_version = 1
epoch = 2.0

[contracts.outdated-bitcoin-degens]
path = 'contracts/outdated-bitcoin-degens.clar'
clarity_version = 1
epoch = 2.0

[contracts.whitelist-fns]
path = 'contracts/whitelist-fns.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
