[project]
name = 'bns-collection'
description = ''
authors = []
telemetry = false
cache_dir = '.cache'
requirements = []
[contracts.bitcoin-degens]
path = 'contracts/bitcoin-degens.clar'
clarity_version = 1
epoch = 2.0

[contracts.bns]
path = 'contracts/bns.clar'
clarity_version = 1
epoch = 2.0

[contracts.bnsx-extensions]
path = 'contracts/bnsx-extensions.clar'
clarity_version = 1
epoch = 2.0

[contracts.bnsx-registry]
path = 'contracts/bnsx-registry.clar'
clarity_version = 1
epoch = 2.0

[contracts.conversions]
path = 'contracts/conversions.clar'
clarity_version = 1
epoch = 2.0

[contracts.extension-trait]
path = 'contracts/extension-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.nft-trait]
path = 'contracts/nft-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.og-bitcoin-degens]
path = 'contracts/og-bitcoin-degens.clar'
clarity_version = 1
epoch = 2.0

[contracts.outdated-bitcoin-degens]
path = 'contracts/outdated-bitcoin-degens.clar'
clarity_version = 1
epoch = 2.0

[contracts.proposal-trait]
path = 'contracts/proposal-trait.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
